[package]
name = "simbiose7-sql"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[features]
default = []
duckdb-sidecar = ["simbiose7-sql-schema/duckdb-sidecar"]
openapi = ["simbiose7-sql-data/openapi", "simbiose7-types/openapi"]

[dependencies]
simbiose7-sql-core = { path = "../simbiose7-sql-core" }
simbiose7-sql-data = { path = "../simbiose7-sql-data" }
simbiose7-sql-dialect = { path = "../simbiose7-sql-dialect" }
simbiose7-sql-schema = { path = "../simbiose7-sql-schema" }
simbiose7-types = { path = "../simbiose7-types", default-features = false }
