[package]
name = "simbiose7-driver-mysql"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[features]
default = []
test-support = []

[dependencies]
simbiose7-driver-support = { path = "../simbiose7-driver-support" }
simbiose7-sql-core = { path = "../simbiose7-sql-core" }
simbiose7-sql-dialect = { path = "../simbiose7-sql-dialect" }
simbiose7-types = { path = "../simbiose7-types", default-features = false }
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
log = "0.4"
mysql_async = { version = "0.37", default-features = false, features = ["default-rustls", "client_ed25519", "chrono", "rust_decimal"] }
percent-encoding = "2"
rust_decimal = { version = "1", features = ["serde"] }
serde_json = { version = "1.0", features = ["arbitrary_precision", "preserve_order"] }
sqlparser = { version = "0.62.0", features = ["visitor"] }
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["compat"] }

[dev-dependencies]
mysql_common = { git = "https://github.com/t8y2/rust_mysql_common.git", rev = "47740d85a8277167a5717afac785d37b46a36296", default-features = false }
