[package]
name = "simbiose7-sql-data"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[features]
default = []
openapi = ["dep:utoipa", "simbiose7-types/openapi"]

[dependencies]
simbiose7-sql-core = { path = "../simbiose7-sql-core" }
simbiose7-sql-dialect = { path = "../simbiose7-sql-dialect" }
simbiose7-types = { path = "../simbiose7-types", default-features = false }
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["arbitrary_precision", "preserve_order"] }
sqlparser = { version = "0.62.0", features = ["visitor"] }
unicode-width = "0.2"
utoipa = { version = "5.5", optional = true }
